version: 0.0
os: linux
files:
  - source: /dist/  # アーティファクト内の「dist」ディレクトリをソースに指定
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/install_apache.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
